/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AgentMarkMessageType model module.
* @module DeskPRO\API/Model/AgentMarkMessageType
* @version 2.0.0
*/
export default class AgentMarkMessageType {
    /**
    * Constructs a new <code>AgentMarkMessageType</code>.
    * @alias module:DeskPRO\API/Model/AgentMarkMessageType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AgentMarkMessageType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:DeskPRO\API/Model/AgentMarkMessageType} obj Optional instance to populate.
    * @return {module:DeskPRO\API/Model/AgentMarkMessageType} The populated <code>AgentMarkMessageType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AgentMarkMessageType();

            
            
            

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['String']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} ids
    */
    ids = undefined;
    /**
    * @member {String} status
    */
    status = undefined;








}


