/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CustomFieldType model module.
* @module DeskPRO\API/Model/CustomFieldType
* @version 2.0.0
*/
export default class CustomFieldType {
    /**
    * Constructs a new <code>CustomFieldType</code>.
    * @alias module:DeskPRO\API/Model/CustomFieldType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CustomFieldType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:DeskPRO\API/Model/CustomFieldType} obj Optional instance to populate.
    * @return {module:DeskPRO\API/Model/CustomFieldType} The populated <code>CustomFieldType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldType();

            
            
            

            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('display_order')) {
                obj['display_order'] = ApiClient.convertToType(data['display_order'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} is_enabled
    */
    is_enabled = undefined;
    /**
    * @member {Number} display_order
    */
    display_order = undefined;








}


