/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The OrganizationNoteType model module.
* @module DeskPRO\API/Model/OrganizationNoteType
* @version 2.0.0
*/
export default class OrganizationNoteType {
    /**
    * Constructs a new <code>OrganizationNoteType</code>.
    * @alias module:DeskPRO\API/Model/OrganizationNoteType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>OrganizationNoteType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:DeskPRO\API/Model/OrganizationNoteType} obj Optional instance to populate.
    * @return {module:DeskPRO\API/Model/OrganizationNoteType} The populated <code>OrganizationNoteType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationNoteType();

            
            
            

            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} note
    */
    note = undefined;








}


