/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PersonOnboardingType model module.
* @module DeskPRO\API/Model/PersonOnboardingType
* @version 2.0.0
*/
export default class PersonOnboardingType {
    /**
    * Constructs a new <code>PersonOnboardingType</code>.
    * @alias module:DeskPRO\API/Model/PersonOnboardingType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PersonOnboardingType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:DeskPRO\API/Model/PersonOnboardingType} obj Optional instance to populate.
    * @return {module:DeskPRO\API/Model/PersonOnboardingType} The populated <code>PersonOnboardingType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonOnboardingType();

            
            
            

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('date_completion')) {
                obj['date_completion'] = ApiClient.convertToType(data['date_completion'], 'String');
            }
            if (data.hasOwnProperty('current_step')) {
                obj['current_step'] = ApiClient.convertToType(data['current_step'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {String} date_completion
    */
    date_completion = undefined;
    /**
    * @member {Number} current_step
    */
    current_step = undefined;








}


