/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TicketWithLayoutsApiType model module.
* @module DeskPRO\API/Model/TicketWithLayoutsApiType
* @version 2.0.0
*/
export default class TicketWithLayoutsApiType {
    /**
    * Constructs a new <code>TicketWithLayoutsApiType</code>.
    * @alias module:DeskPRO\API/Model/TicketWithLayoutsApiType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TicketWithLayoutsApiType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:DeskPRO\API/Model/TicketWithLayoutsApiType} obj Optional instance to populate.
    * @return {module:DeskPRO\API/Model/TicketWithLayoutsApiType} The populated <code>TicketWithLayoutsApiType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TicketWithLayoutsApiType();

            
            
            

            if (data.hasOwnProperty('person')) {
                obj['person'] = ApiClient.convertToType(data['person'], Object);
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], Object);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [Object]);
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Object} person
    */
    person = undefined;
    /**
    * @member {String} department
    */
    department = undefined;
    /**
    * @member {String} subject
    */
    subject = undefined;
    /**
    * @member {Object} message
    */
    message = undefined;
    /**
    * @member {Array.<Object>} attachments
    */
    attachments = undefined;
    /**
    * @member {Array.<String>} labels
    */
    labels = undefined;








}


