/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../Model/Error';
import Response from '../Model/Response';

/**
* ClientDevices service.
* @module DeskPRO\API/Client/ClientDevicesApi
* @version 2.0.0
*/
export default class ClientDevicesApi {

    /**
    * Constructs a new ClientDevicesApi. 
    * @alias module:DeskPRO\API/Client/ClientDevicesApi
    * @class
    * @param {module:DeskPRO\API/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:DeskPRO\API/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteClientDeviceByAppTypeById operation.
     * @callback module:DeskPRO\API/Client/ClientDevicesApi~deleteClientDeviceByAppTypeByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:DeskPRO\API/Model/Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a resource
     * @param {Number} id The id or device_id of the resource
     * @param {String} appType 
     * @param {module:DeskPRO\API/Client/ClientDevicesApi~deleteClientDeviceByAppTypeByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:DeskPRO\API/Model/Response}
     */
    deleteClientDeviceByAppTypeById(id, appType, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteClientDeviceByAppTypeById");
      }

      // verify the required parameter 'appType' is set
      if (appType === undefined || appType === null) {
        throw new Error("Missing the required parameter 'appType' when calling deleteClientDeviceByAppTypeById");
      }


      let pathParams = {
        'id': id,
        'app_type': appType
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/client_devices/{app_type}/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getClientDeviceByAppType operation.
     * @callback module:DeskPRO\API/Client/ClientDevicesApi~getClientDeviceByAppTypeCallback
     * @param {String} error Error message, if any.
     * @param {module:DeskPRO\API/Model/Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get collection of resources
     * @param {String} appType 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page Which page to display
     * @param {Number} opts.count Resource per page count
     * @param {Number} opts.limit Max number of resources to return
     * @param {String} opts.ids Comma separated list of IDs
     * @param {module:DeskPRO\API/Client/ClientDevicesApi~getClientDeviceByAppTypeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:DeskPRO\API/Model/Response}
     */
    getClientDeviceByAppType(appType, opts, callback) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'appType' is set
      if (appType === undefined || appType === null) {
        throw new Error("Missing the required parameter 'appType' when calling getClientDeviceByAppType");
      }


      let pathParams = {
        'app_type': appType
      };
      let queryParams = {
        'page': opts['page'],
        'count': opts['count'],
        'limit': opts['limit'],
        'ids': opts['ids']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/client_devices/{app_type}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getClientDeviceByAppTypeById operation.
     * @callback module:DeskPRO\API/Client/ClientDevicesApi~getClientDeviceByAppTypeByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:DeskPRO\API/Model/Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a resource
     * @param {Number} id The id or device_id of the resource
     * @param {String} appType 
     * @param {module:DeskPRO\API/Client/ClientDevicesApi~getClientDeviceByAppTypeByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:DeskPRO\API/Model/Response}
     */
    getClientDeviceByAppTypeById(id, appType, callback) {
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getClientDeviceByAppTypeById");
      }

      // verify the required parameter 'appType' is set
      if (appType === undefined || appType === null) {
        throw new Error("Missing the required parameter 'appType' when calling getClientDeviceByAppTypeById");
      }


      let pathParams = {
        'id': id,
        'app_type': appType
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/client_devices/{app_type}/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getClientDeviceByAppTypeCount operation.
     * @callback module:DeskPRO\API/Client/ClientDevicesApi~getClientDeviceByAppTypeCountCallback
     * @param {String} error Error message, if any.
     * @param {module:DeskPRO\API/Model/Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Count list
     * @param {String} appType 
     * @param {module:DeskPRO\API/Client/ClientDevicesApi~getClientDeviceByAppTypeCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:DeskPRO\API/Model/Response}
     */
    getClientDeviceByAppTypeCount(appType, callback) {
      let postBody = null;

      // verify the required parameter 'appType' is set
      if (appType === undefined || appType === null) {
        throw new Error("Missing the required parameter 'appType' when calling getClientDeviceByAppTypeCount");
      }


      let pathParams = {
        'app_type': appType
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/client_devices/{app_type}/counts', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
