/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AppInstance model module.
* @module model/AppInstance
* @version 2.0.0
*/
export default class AppInstance {
    /**
    * Constructs a new <code>AppInstance</code>.
    * @alias module:model/AppInstance
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AppInstance</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AppInstance} obj Optional instance to populate.
    * @return {module:model/AppInstance} The populated <code>AppInstance</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppInstance();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('is_installed')) {
                obj['is_installed'] = ApiClient.convertToType(data['is_installed'], 'Boolean');
            }
            if (data.hasOwnProperty('app')) {
                obj['app'] = ApiClient.convertToType(data['app'], 'Number');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = ApiClient.convertToType(data['settings'], [Object]);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Boolean} is_installed
    */
    is_installed = undefined;
    /**
    * @member {Number} app
    */
    app = undefined;
    /**
    * @member {String} scope
    */
    scope = undefined;
    /**
    * @member {Array.<Object>} settings
    */
    settings = undefined;
    /**
    * @member {String} created_at
    */
    created_at = undefined;








}


