/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ArticleType model module.
* @module model/ArticleType
* @version 2.0.0
*/
export default class ArticleType {
    /**
    * Constructs a new <code>ArticleType</code>.
    * @alias module:model/ArticleType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ArticleType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ArticleType} obj Optional instance to populate.
    * @return {module:model/ArticleType} The populated <code>ArticleType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArticleType();

            
            
            

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('person')) {
                obj['person'] = ApiClient.convertToType(data['person'], Object);
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('content_input_type')) {
                obj['content_input_type'] = ApiClient.convertToType(data['content_input_type'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('title_translations')) {
                obj['title_translations'] = ApiClient.convertToType(data['title_translations'], [Object]);
            }
            if (data.hasOwnProperty('content_translations')) {
                obj['content_translations'] = ApiClient.convertToType(data['content_translations'], [Object]);
            }
            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {String} content
    */
    content = undefined;
    /**
    * @member {Object} person
    */
    person = undefined;
    /**
    * @member {String} language
    */
    language = undefined;
    /**
    * @member {String} content_input_type
    */
    content_input_type = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {Array.<Object>} title_translations
    */
    title_translations = undefined;
    /**
    * @member {Array.<Object>} content_translations
    */
    content_translations = undefined;
    /**
    * @member {Array.<String>} categories
    */
    categories = undefined;








}


