/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The BlobAuthType model module.
* @module model/BlobAuthType
* @version 2.0.0
*/
export default class BlobAuthType {
    /**
    * Constructs a new <code>BlobAuthType</code>.
    * @alias module:model/BlobAuthType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>BlobAuthType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BlobAuthType} obj Optional instance to populate.
    * @return {module:model/BlobAuthType} The populated <code>BlobAuthType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlobAuthType();

            
            
            

        }
        return obj;
    }









}


