/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ChatConversationType model module.
* @module model/ChatConversationType
* @version 2.0.0
*/
export default class ChatConversationType {
    /**
    * Constructs a new <code>ChatConversationType</code>.
    * @alias module:model/ChatConversationType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ChatConversationType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ChatConversationType} obj Optional instance to populate.
    * @return {module:model/ChatConversationType} The populated <code>ChatConversationType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChatConversationType();

            
            
            

            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('person')) {
                obj['person'] = ApiClient.convertToType(data['person'], Object);
            }
            if (data.hasOwnProperty('person_email')) {
                obj['person_email'] = ApiClient.convertToType(data['person_email'], 'String');
            }
            if (data.hasOwnProperty('agent')) {
                obj['agent'] = ApiClient.convertToType(data['agent'], Object);
            }
            if (data.hasOwnProperty('email_validated')) {
                obj['email_validated'] = ApiClient.convertToType(data['email_validated'], 'Boolean');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], Object);
            }
            if (data.hasOwnProperty('chat_department')) {
                obj['chat_department'] = ApiClient.convertToType(data['chat_department'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} subject
    */
    subject = undefined;
    /**
    * @member {Object} person
    */
    person = undefined;
    /**
    * @member {String} person_email
    */
    person_email = undefined;
    /**
    * @member {Object} agent
    */
    agent = undefined;
    /**
    * @member {Boolean} email_validated
    */
    email_validated = undefined;
    /**
    * @member {Object} fields
    */
    fields = undefined;
    /**
    * @member {String} chat_department
    */
    chat_department = undefined;








}


