/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The DownloadType model module.
* @module model/DownloadType
* @version 2.0.0
*/
export default class DownloadType {
    /**
    * Constructs a new <code>DownloadType</code>.
    * @alias module:model/DownloadType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>DownloadType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DownloadType} obj Optional instance to populate.
    * @return {module:model/DownloadType} The populated <code>DownloadType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DownloadType();

            
            
            

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('person')) {
                obj['person'] = ApiClient.convertToType(data['person'], Object);
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('content_input_type')) {
                obj['content_input_type'] = ApiClient.convertToType(data['content_input_type'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('blob')) {
                obj['blob'] = ApiClient.convertToType(data['blob'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {String} content
    */
    content = undefined;
    /**
    * @member {Object} person
    */
    person = undefined;
    /**
    * @member {String} language
    */
    language = undefined;
    /**
    * @member {String} content_input_type
    */
    content_input_type = undefined;
    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {String} blob
    */
    blob = undefined;
    /**
    * @member {String} category
    */
    category = undefined;








}


