/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The FeedbackCommentType model module.
* @module model/FeedbackCommentType
* @version 2.0.0
*/
export default class FeedbackCommentType {
    /**
    * Constructs a new <code>FeedbackCommentType</code>.
    * @alias module:model/FeedbackCommentType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>FeedbackCommentType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FeedbackCommentType} obj Optional instance to populate.
    * @return {module:model/FeedbackCommentType} The populated <code>FeedbackCommentType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeedbackCommentType();

            
            
            

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('is_reviewed')) {
                obj['is_reviewed'] = ApiClient.convertToType(data['is_reviewed'], 'Boolean');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} status
    */
    status = undefined;
    /**
    * @member {Boolean} is_reviewed
    */
    is_reviewed = undefined;
    /**
    * @member {String} content
    */
    content = undefined;








}


