/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import GlossaryWordType from './GlossaryWordType';





/**
* The GlossaryWordDefinitionType model module.
* @module model/GlossaryWordDefinitionType
* @version 2.0.0
*/
export default class GlossaryWordDefinitionType {
    /**
    * Constructs a new <code>GlossaryWordDefinitionType</code>.
    * @alias module:model/GlossaryWordDefinitionType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>GlossaryWordDefinitionType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GlossaryWordDefinitionType} obj Optional instance to populate.
    * @return {module:model/GlossaryWordDefinitionType} The populated <code>GlossaryWordDefinitionType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GlossaryWordDefinitionType();

            
            
            

            if (data.hasOwnProperty('definition')) {
                obj['definition'] = ApiClient.convertToType(data['definition'], 'String');
            }
            if (data.hasOwnProperty('words')) {
                obj['words'] = ApiClient.convertToType(data['words'], [GlossaryWordType]);
            }
        }
        return obj;
    }

    /**
    * @member {String} definition
    */
    definition = undefined;
    /**
    * @member {Array.<module:model/GlossaryWordType>} words
    */
    words = undefined;








}


