/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The OrganizationType model module.
* @module model/OrganizationType
* @version 2.0.0
*/
export default class OrganizationType {
    /**
    * Constructs a new <code>OrganizationType</code>.
    * @alias module:model/OrganizationType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>OrganizationType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OrganizationType} obj Optional instance to populate.
    * @return {module:model/OrganizationType} The populated <code>OrganizationType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationType();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = ApiClient.convertToType(data['parent'], 'String');
            }
            if (data.hasOwnProperty('picture_blob')) {
                obj['picture_blob'] = ApiClient.convertToType(data['picture_blob'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('importance')) {
                obj['importance'] = ApiClient.convertToType(data['importance'], 'Number');
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], ['String']);
            }
            if (data.hasOwnProperty('user_groups')) {
                obj['user_groups'] = ApiClient.convertToType(data['user_groups'], ['String']);
            }
            if (data.hasOwnProperty('email_domains')) {
                obj['email_domains'] = ApiClient.convertToType(data['email_domains'], ['String']);
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], Object);
            }
            if (data.hasOwnProperty('contact_data')) {
                obj['contact_data'] = ApiClient.convertToType(data['contact_data'], Object);
            }
            if (data.hasOwnProperty('members')) {
                obj['members'] = ApiClient.convertToType(data['members'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} parent
    */
    parent = undefined;
    /**
    * @member {String} picture_blob
    */
    picture_blob = undefined;
    /**
    * @member {String} summary
    */
    summary = undefined;
    /**
    * @member {Number} importance
    */
    importance = undefined;
    /**
    * @member {Array.<String>} labels
    */
    labels = undefined;
    /**
    * @member {Array.<String>} user_groups
    */
    user_groups = undefined;
    /**
    * @member {Array.<String>} email_domains
    */
    email_domains = undefined;
    /**
    * @member {Object} fields
    */
    fields = undefined;
    /**
    * @member {Object} contact_data
    */
    contact_data = undefined;
    /**
    * @member {Array.<String>} members
    */
    members = undefined;








}


