/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TicketStarNameType model module.
* @module model/TicketStarNameType
* @version 2.0.0
*/
export default class TicketStarNameType {
    /**
    * Constructs a new <code>TicketStarNameType</code>.
    * @alias module:model/TicketStarNameType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TicketStarNameType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TicketStarNameType} obj Optional instance to populate.
    * @return {module:model/TicketStarNameType} The populated <code>TicketStarNameType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TicketStarNameType();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;








}


