/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The WidgetSettingsType model module.
* @module model/WidgetSettingsType
* @version 2.0.0
*/
export default class WidgetSettingsType {
    /**
    * Constructs a new <code>WidgetSettingsType</code>.
    * @alias module:model/WidgetSettingsType
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>WidgetSettingsType</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/WidgetSettingsType} obj Optional instance to populate.
    * @return {module:model/WidgetSettingsType} The populated <code>WidgetSettingsType</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WidgetSettingsType();

            
            
            

            if (data.hasOwnProperty('settings')) {
                obj['settings'] = ApiClient.convertToType(data['settings'], Object);
            }
            if (data.hasOwnProperty('enabled_on_portal')) {
                obj['enabled_on_portal'] = ApiClient.convertToType(data['enabled_on_portal'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {Object} settings
    */
    settings = undefined;
    /**
    * @member {Boolean} enabled_on_portal
    */
    enabled_on_portal = undefined;








}


