/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import Response from '../model/Response';

/**
* Logs service.
* @module api/LogsApi
* @version 2.0.0
*/
export default class LogsApi {

    /**
    * Constructs a new LogsApi. 
    * @alias module:api/LogsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * get api log
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.page 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Response} and HTTP response
     */
    getApiLogByIdWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getApiLogById");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
        'page': opts['page']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/api_logs/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * get api log
     * @param {String} id 
     * @param {Object} opts Optional parameters
     * @param {String} opts.page 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Response}
     */
    getApiLogById(id, opts) {
      return this.getApiLogByIdWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * get api logs collection
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Response} and HTTP response
     */
    getApiLogsWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/api_logs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * get api logs collection
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Response}
     */
    getApiLogs() {
      return this.getApiLogsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * get logging options
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Response} and HTTP response
     */
    getApiLogsOptionsWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/api_logs_options', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * get logging options
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Response}
     */
    getApiLogsOptions() {
      return this.getApiLogsOptionsWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * update logging options
     * @param {Number} id id of entry to replay
     * @param {Object} opts Optional parameters
     * @param {String} opts.mode how to replay
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Response} and HTTP response
     */
    setApiLogByIdReplayWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling setApiLogByIdReplay");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
        'mode': opts['mode']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/api_logs/{id}/replay', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * update logging options
     * @param {Number} id id of entry to replay
     * @param {Object} opts Optional parameters
     * @param {String} opts.mode how to replay
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Response}
     */
    setApiLogByIdReplay(id, opts) {
      return this.setApiLogByIdReplayWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * update logging options
     * @param {Number} requestLength 
     * @param {Number} responseLength 
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.enabled provide 1 if you want to enable logging
     * @param {Array.<String>} opts.modes strings array, values are session, key, token
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Response} and HTTP response
     */
    updateApiLogsOptionsWithHttpInfo(requestLength, responseLength, opts) {
      opts = opts || {};
      let postBody = null;

      // verify the required parameter 'requestLength' is set
      if (requestLength === undefined || requestLength === null) {
        throw new Error("Missing the required parameter 'requestLength' when calling updateApiLogsOptions");
      }

      // verify the required parameter 'responseLength' is set
      if (responseLength === undefined || responseLength === null) {
        throw new Error("Missing the required parameter 'responseLength' when calling updateApiLogsOptions");
      }


      let pathParams = {
      };
      let queryParams = {
        'enabled': opts['enabled'],
        'modes': this.apiClient.buildCollectionParam(opts['modes'], 'csv'),
        'request_length': requestLength,
        'response_length': responseLength
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['KeyAuthentication'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Response;

      return this.apiClient.callApi(
        '/api_logs_options', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * update logging options
     * @param {Number} requestLength 
     * @param {Number} responseLength 
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.enabled provide 1 if you want to enable logging
     * @param {Array.<String>} opts.modes strings array, values are session, key, token
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Response}
     */
    updateApiLogsOptions(requestLength, responseLength, opts) {
      return this.updateApiLogsOptionsWithHttpInfo(requestLength, responseLength, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
