/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeskProApi);
  }
}(this, function(expect, DeskProApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeskProApi.ArticleType();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArticleType', function() {
    it('should create an instance of ArticleType', function() {
      // uncomment below and update the code to test ArticleType
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be.a(DeskProApi.ArticleType);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

    it('should have the property person (base name: "person")', function() {
      // uncomment below and update the code to test the property person
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

    it('should have the property contentInputType (base name: "content_input_type")', function() {
      // uncomment below and update the code to test the property contentInputType
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

    it('should have the property titleTranslations (base name: "title_translations")', function() {
      // uncomment below and update the code to test the property titleTranslations
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

    it('should have the property contentTranslations (base name: "content_translations")', function() {
      // uncomment below and update the code to test the property contentTranslations
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

    it('should have the property categories (base name: "categories")', function() {
      // uncomment below and update the code to test the property categories
      //var instane = new DeskProApi.ArticleType();
      //expect(instance).to.be();
    });

  });

}));
