/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeskProApi);
  }
}(this, function(expect, DeskProApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeskProApi.CaptchaAntiAbuseType();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CaptchaAntiAbuseType', function() {
    it('should create an instance of CaptchaAntiAbuseType', function() {
      // uncomment below and update the code to test CaptchaAntiAbuseType
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be.a(DeskProApi.CaptchaAntiAbuseType);
    });

    it('should have the property useRecaptcha2 (base name: "use_recaptcha2")', function() {
      // uncomment below and update the code to test the property useRecaptcha2
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be();
    });

    it('should have the property recaptcha2SiteKey (base name: "recaptcha2_site_key")', function() {
      // uncomment below and update the code to test the property recaptcha2SiteKey
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be();
    });

    it('should have the property recaptcha2SecretKey (base name: "recaptcha2_secret_key")', function() {
      // uncomment below and update the code to test the property recaptcha2SecretKey
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be();
    });

    it('should have the property tickets (base name: "tickets")', function() {
      // uncomment below and update the code to test the property tickets
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be();
    });

    it('should have the property feedback (base name: "feedback")', function() {
      // uncomment below and update the code to test the property feedback
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be();
    });

    it('should have the property register (base name: "register")', function() {
      // uncomment below and update the code to test the property register
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be();
    });

    it('should have the property sharing (base name: "sharing")', function() {
      // uncomment below and update the code to test the property sharing
      //var instane = new DeskProApi.CaptchaAntiAbuseType();
      //expect(instance).to.be();
    });

  });

}));
