/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeskProApi);
  }
}(this, function(expect, DeskProApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeskProApi.ClientDeviceType();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClientDeviceType', function() {
    it('should create an instance of ClientDeviceType', function() {
      // uncomment below and update the code to test ClientDeviceType
      //var instane = new DeskProApi.ClientDeviceType();
      //expect(instance).to.be.a(DeskProApi.ClientDeviceType);
    });

    it('should have the property deviceId (base name: "device_id")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instane = new DeskProApi.ClientDeviceType();
      //expect(instance).to.be();
    });

    it('should have the property deviceType (base name: "device_type")', function() {
      // uncomment below and update the code to test the property deviceType
      //var instane = new DeskProApi.ClientDeviceType();
      //expect(instance).to.be();
    });

    it('should have the property deviceAgent (base name: "device_agent")', function() {
      // uncomment below and update the code to test the property deviceAgent
      //var instane = new DeskProApi.ClientDeviceType();
      //expect(instance).to.be();
    });

    it('should have the property deviceName (base name: "device_name")', function() {
      // uncomment below and update the code to test the property deviceName
      //var instane = new DeskProApi.ClientDeviceType();
      //expect(instance).to.be();
    });

    it('should have the property notificationToken (base name: "notification_token")', function() {
      // uncomment below and update the code to test the property notificationToken
      //var instane = new DeskProApi.ClientDeviceType();
      //expect(instance).to.be();
    });

  });

}));
