/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeskProApi);
  }
}(this, function(expect, DeskProApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeskProApi.DepartmentType();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DepartmentType', function() {
    it('should create an instance of DepartmentType', function() {
      // uncomment below and update the code to test DepartmentType
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be.a(DeskProApi.DepartmentType);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be();
    });

    it('should have the property userTitle (base name: "user_title")', function() {
      // uncomment below and update the code to test the property userTitle
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be();
    });

    it('should have the property parent (base name: "parent")', function() {
      // uncomment below and update the code to test the property parent
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be();
    });

    it('should have the property avatar (base name: "avatar")', function() {
      // uncomment below and update the code to test the property avatar
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be();
    });

    it('should have the property displayOrder (base name: "display_order")', function() {
      // uncomment below and update the code to test the property displayOrder
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be();
    });

    it('should have the property isTicketsEnabled (base name: "is_tickets_enabled")', function() {
      // uncomment below and update the code to test the property isTicketsEnabled
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be();
    });

    it('should have the property isChatEnabled (base name: "is_chat_enabled")', function() {
      // uncomment below and update the code to test the property isChatEnabled
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be();
    });

    it('should have the property brands (base name: "brands")', function() {
      // uncomment below and update the code to test the property brands
      //var instane = new DeskProApi.DepartmentType();
      //expect(instance).to.be();
    });

  });

}));
