/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeskProApi);
  }
}(this, function(expect, DeskProApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeskProApi.ContentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContentApi', function() {
    describe('deleteArticleById', function() {
      it('should call deleteArticleById successfully', function(done) {
        //uncomment below and update the code to test deleteArticleById
        //instance.deleteArticleById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteArticleCategoryById', function() {
      it('should call deleteArticleCategoryById successfully', function(done) {
        //uncomment below and update the code to test deleteArticleCategoryById
        //instance.deleteArticleCategoryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteArticleCommentById', function() {
      it('should call deleteArticleCommentById successfully', function(done) {
        //uncomment below and update the code to test deleteArticleCommentById
        //instance.deleteArticleCommentById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteArticlePendingCreateById', function() {
      it('should call deleteArticlePendingCreateById successfully', function(done) {
        //uncomment below and update the code to test deleteArticlePendingCreateById
        //instance.deleteArticlePendingCreateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDownloadById', function() {
      it('should call deleteDownloadById successfully', function(done) {
        //uncomment below and update the code to test deleteDownloadById
        //instance.deleteDownloadById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDownloadCategoryById', function() {
      it('should call deleteDownloadCategoryById successfully', function(done) {
        //uncomment below and update the code to test deleteDownloadCategoryById
        //instance.deleteDownloadCategoryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDownloadCommentById', function() {
      it('should call deleteDownloadCommentById successfully', function(done) {
        //uncomment below and update the code to test deleteDownloadCommentById
        //instance.deleteDownloadCommentById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteGuideById', function() {
      it('should call deleteGuideById successfully', function(done) {
        //uncomment below and update the code to test deleteGuideById
        //instance.deleteGuideById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNewsById', function() {
      it('should call deleteNewsById successfully', function(done) {
        //uncomment below and update the code to test deleteNewsById
        //instance.deleteNewsById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNewsCategoryById', function() {
      it('should call deleteNewsCategoryById successfully', function(done) {
        //uncomment below and update the code to test deleteNewsCategoryById
        //instance.deleteNewsCategoryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNewsCommentById', function() {
      it('should call deleteNewsCommentById successfully', function(done) {
        //uncomment below and update the code to test deleteNewsCommentById
        //instance.deleteNewsCommentById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTopicById', function() {
      it('should call deleteTopicById successfully', function(done) {
        //uncomment below and update the code to test deleteTopicById
        //instance.deleteTopicById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticleById', function() {
      it('should call getArticleById successfully', function(done) {
        //uncomment below and update the code to test getArticleById
        //instance.getArticleById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticleCategories', function() {
      it('should call getArticleCategories successfully', function(done) {
        //uncomment below and update the code to test getArticleCategories
        //instance.getArticleCategories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticleCategoryById', function() {
      it('should call getArticleCategoryById successfully', function(done) {
        //uncomment below and update the code to test getArticleCategoryById
        //instance.getArticleCategoryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticleCategoryCount', function() {
      it('should call getArticleCategoryCount successfully', function(done) {
        //uncomment below and update the code to test getArticleCategoryCount
        //instance.getArticleCategoryCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticleCommentById', function() {
      it('should call getArticleCommentById successfully', function(done) {
        //uncomment below and update the code to test getArticleCommentById
        //instance.getArticleCommentById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticleCommentCount', function() {
      it('should call getArticleCommentCount successfully', function(done) {
        //uncomment below and update the code to test getArticleCommentCount
        //instance.getArticleCommentCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticleComments', function() {
      it('should call getArticleComments successfully', function(done) {
        //uncomment below and update the code to test getArticleComments
        //instance.getArticleComments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticleCount', function() {
      it('should call getArticleCount successfully', function(done) {
        //uncomment below and update the code to test getArticleCount
        //instance.getArticleCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticlePendingCreateById', function() {
      it('should call getArticlePendingCreateById successfully', function(done) {
        //uncomment below and update the code to test getArticlePendingCreateById
        //instance.getArticlePendingCreateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticlePendingCreateCount', function() {
      it('should call getArticlePendingCreateCount successfully', function(done) {
        //uncomment below and update the code to test getArticlePendingCreateCount
        //instance.getArticlePendingCreateCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticlePendingCreates', function() {
      it('should call getArticlePendingCreates successfully', function(done) {
        //uncomment below and update the code to test getArticlePendingCreates
        //instance.getArticlePendingCreates(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticles', function() {
      it('should call getArticles successfully', function(done) {
        //uncomment below and update the code to test getArticles
        //instance.getArticles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContentCategories', function() {
      it('should call getContentCategories successfully', function(done) {
        //uncomment below and update the code to test getContentCategories
        //instance.getContentCategories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloadById', function() {
      it('should call getDownloadById successfully', function(done) {
        //uncomment below and update the code to test getDownloadById
        //instance.getDownloadById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloadCategories', function() {
      it('should call getDownloadCategories successfully', function(done) {
        //uncomment below and update the code to test getDownloadCategories
        //instance.getDownloadCategories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloadCategoryById', function() {
      it('should call getDownloadCategoryById successfully', function(done) {
        //uncomment below and update the code to test getDownloadCategoryById
        //instance.getDownloadCategoryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloadCategoryCount', function() {
      it('should call getDownloadCategoryCount successfully', function(done) {
        //uncomment below and update the code to test getDownloadCategoryCount
        //instance.getDownloadCategoryCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloadCommentById', function() {
      it('should call getDownloadCommentById successfully', function(done) {
        //uncomment below and update the code to test getDownloadCommentById
        //instance.getDownloadCommentById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloadCommentCount', function() {
      it('should call getDownloadCommentCount successfully', function(done) {
        //uncomment below and update the code to test getDownloadCommentCount
        //instance.getDownloadCommentCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloadComments', function() {
      it('should call getDownloadComments successfully', function(done) {
        //uncomment below and update the code to test getDownloadComments
        //instance.getDownloadComments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloadCount', function() {
      it('should call getDownloadCount successfully', function(done) {
        //uncomment below and update the code to test getDownloadCount
        //instance.getDownloadCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDownloads', function() {
      it('should call getDownloads successfully', function(done) {
        //uncomment below and update the code to test getDownloads
        //instance.getDownloads(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGuideByGuideIdExport', function() {
      it('should call getGuideByGuideIdExport successfully', function(done) {
        //uncomment below and update the code to test getGuideByGuideIdExport
        //instance.getGuideByGuideIdExport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGuideByGuideIdTree', function() {
      it('should call getGuideByGuideIdTree successfully', function(done) {
        //uncomment below and update the code to test getGuideByGuideIdTree
        //instance.getGuideByGuideIdTree(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGuideById', function() {
      it('should call getGuideById successfully', function(done) {
        //uncomment below and update the code to test getGuideById
        //instance.getGuideById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGuideCount', function() {
      it('should call getGuideCount successfully', function(done) {
        //uncomment below and update the code to test getGuideCount
        //instance.getGuideCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGuides', function() {
      it('should call getGuides successfully', function(done) {
        //uncomment below and update the code to test getGuides
        //instance.getGuides(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNews', function() {
      it('should call getNews successfully', function(done) {
        //uncomment below and update the code to test getNews
        //instance.getNews(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsById', function() {
      it('should call getNewsById successfully', function(done) {
        //uncomment below and update the code to test getNewsById
        //instance.getNewsById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsCategories', function() {
      it('should call getNewsCategories successfully', function(done) {
        //uncomment below and update the code to test getNewsCategories
        //instance.getNewsCategories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsCategoryById', function() {
      it('should call getNewsCategoryById successfully', function(done) {
        //uncomment below and update the code to test getNewsCategoryById
        //instance.getNewsCategoryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsCategoryCount', function() {
      it('should call getNewsCategoryCount successfully', function(done) {
        //uncomment below and update the code to test getNewsCategoryCount
        //instance.getNewsCategoryCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsCommentById', function() {
      it('should call getNewsCommentById successfully', function(done) {
        //uncomment below and update the code to test getNewsCommentById
        //instance.getNewsCommentById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsCommentCount', function() {
      it('should call getNewsCommentCount successfully', function(done) {
        //uncomment below and update the code to test getNewsCommentCount
        //instance.getNewsCommentCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsComments', function() {
      it('should call getNewsComments successfully', function(done) {
        //uncomment below and update the code to test getNewsComments
        //instance.getNewsComments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNewsCount', function() {
      it('should call getNewsCount successfully', function(done) {
        //uncomment below and update the code to test getNewsCount
        //instance.getNewsCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTopicById', function() {
      it('should call getTopicById successfully', function(done) {
        //uncomment below and update the code to test getTopicById
        //instance.getTopicById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTopicCount', function() {
      it('should call getTopicCount successfully', function(done) {
        //uncomment below and update the code to test getTopicCount
        //instance.getTopicCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTopics', function() {
      it('should call getTopics successfully', function(done) {
        //uncomment below and update the code to test getTopics
        //instance.getTopics(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateGuideByGuideIdTree', function() {
      it('should call updateGuideByGuideIdTree successfully', function(done) {
        //uncomment below and update the code to test updateGuideByGuideIdTree
        //instance.updateGuideByGuideIdTree(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
