/**
 * DeskPRO API
 * DeskPRO API
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DeskProApi);
  }
}(this, function(expect, DeskProApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DeskProApi.TicketsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TicketsApi', function() {
    describe('deleteTicketById', function() {
      it('should call deleteTicketById successfully', function(done) {
        //uncomment below and update the code to test deleteTicketById
        //instance.deleteTicketById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicketByParentIdCcById', function() {
      it('should call deleteTicketByParentIdCcById successfully', function(done) {
        //uncomment below and update the code to test deleteTicketByParentIdCcById
        //instance.deleteTicketByParentIdCcById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicketByParentIdMessageById', function() {
      it('should call deleteTicketByParentIdMessageById successfully', function(done) {
        //uncomment below and update the code to test deleteTicketByParentIdMessageById
        //instance.deleteTicketByParentIdMessageById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicketByParentIdTicketSlaById', function() {
      it('should call deleteTicketByParentIdTicketSlaById successfully', function(done) {
        //uncomment below and update the code to test deleteTicketByParentIdTicketSlaById
        //instance.deleteTicketByParentIdTicketSlaById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicketByParentIdTicketSlaBySlaBySlaId', function() {
      it('should call deleteTicketByParentIdTicketSlaBySlaBySlaId successfully', function(done) {
        //uncomment below and update the code to test deleteTicketByParentIdTicketSlaBySlaBySlaId
        //instance.deleteTicketByParentIdTicketSlaBySlaBySlaId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicketByTicketFollowUpById', function() {
      it('should call deleteTicketByTicketFollowUpById successfully', function(done) {
        //uncomment below and update the code to test deleteTicketByTicketFollowUpById
        //instance.deleteTicketByTicketFollowUpById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicketByTicketLink', function() {
      it('should call deleteTicketByTicketLink successfully', function(done) {
        //uncomment below and update the code to test deleteTicketByTicketLink
        //instance.deleteTicketByTicketLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicketCustomFieldById', function() {
      it('should call deleteTicketCustomFieldById successfully', function(done) {
        //uncomment below and update the code to test deleteTicketCustomFieldById
        //instance.deleteTicketCustomFieldById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTicketProblemById', function() {
      it('should call deleteTicketProblemById successfully', function(done) {
        //uncomment below and update the code to test deleteTicketProblemById
        //instance.deleteTicketProblemById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('get20170401TicketLayoutByContext', function() {
      it('should call get20170401TicketLayoutByContext successfully', function(done) {
        //uncomment below and update the code to test get20170401TicketLayoutByContext
        //instance.get20170401TicketLayoutByContext(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('get20170401TicketLayoutByContextByDepartment', function() {
      it('should call get20170401TicketLayoutByContextByDepartment successfully', function(done) {
        //uncomment below and update the code to test get20170401TicketLayoutByContextByDepartment
        //instance.get20170401TicketLayoutByContextByDepartment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('get20170401TicketLayoutByContextDepartmentJ', function() {
      it('should call get20170401TicketLayoutByContextDepartmentJ successfully', function(done) {
        //uncomment below and update the code to test get20170401TicketLayoutByContextDepartmentJ
        //instance.get20170401TicketLayoutByContextDepartmentJ(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('get20170401TicketLayoutContextJ', function() {
      it('should call get20170401TicketLayoutContextJ successfully', function(done) {
        //uncomment below and update the code to test get20170401TicketLayoutContextJ
        //instance.get20170401TicketLayoutContextJ(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketById', function() {
      it('should call getTicketById successfully', function(done) {
        //uncomment below and update the code to test getTicketById
        //instance.getTicketById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdAttachment', function() {
      it('should call getTicketByParentIdAttachment successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdAttachment
        //instance.getTicketByParentIdAttachment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdCc', function() {
      it('should call getTicketByParentIdCc successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdCc
        //instance.getTicketByParentIdCc(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdCcById', function() {
      it('should call getTicketByParentIdCcById successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdCcById
        //instance.getTicketByParentIdCcById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdLog', function() {
      it('should call getTicketByParentIdLog successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdLog
        //instance.getTicketByParentIdLog(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdLogById', function() {
      it('should call getTicketByParentIdLogById successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdLogById
        //instance.getTicketByParentIdLogById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdLogCount', function() {
      it('should call getTicketByParentIdLogCount successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdLogCount
        //instance.getTicketByParentIdLogCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdMessage', function() {
      it('should call getTicketByParentIdMessage successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdMessage
        //instance.getTicketByParentIdMessage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdMessageById', function() {
      it('should call getTicketByParentIdMessageById successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdMessageById
        //instance.getTicketByParentIdMessageById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdMessageByIdAttachment', function() {
      it('should call getTicketByParentIdMessageByIdAttachment successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdMessageByIdAttachment
        //instance.getTicketByParentIdMessageByIdAttachment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdMessageCount', function() {
      it('should call getTicketByParentIdMessageCount successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdMessageCount
        //instance.getTicketByParentIdMessageCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdTicketSla', function() {
      it('should call getTicketByParentIdTicketSla successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdTicketSla
        //instance.getTicketByParentIdTicketSla(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdTicketSlaById', function() {
      it('should call getTicketByParentIdTicketSlaById successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdTicketSlaById
        //instance.getTicketByParentIdTicketSlaById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdTicketSlaBySlaBySlaId', function() {
      it('should call getTicketByParentIdTicketSlaBySlaBySlaId successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdTicketSlaBySlaBySlaId
        //instance.getTicketByParentIdTicketSlaBySlaBySlaId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByParentIdTicketSlaCount', function() {
      it('should call getTicketByParentIdTicketSlaCount successfully', function(done) {
        //uncomment below and update the code to test getTicketByParentIdTicketSlaCount
        //instance.getTicketByParentIdTicketSlaCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByTicketFollowUp', function() {
      it('should call getTicketByTicketFollowUp successfully', function(done) {
        //uncomment below and update the code to test getTicketByTicketFollowUp
        //instance.getTicketByTicketFollowUp(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByTicketFollowUpById', function() {
      it('should call getTicketByTicketFollowUpById successfully', function(done) {
        //uncomment below and update the code to test getTicketByTicketFollowUpById
        //instance.getTicketByTicketFollowUpById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByTicketFollowUpCount', function() {
      it('should call getTicketByTicketFollowUpCount successfully', function(done) {
        //uncomment below and update the code to test getTicketByTicketFollowUpCount
        //instance.getTicketByTicketFollowUpCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketByTicketLink', function() {
      it('should call getTicketByTicketLink successfully', function(done) {
        //uncomment below and update the code to test getTicketByTicketLink
        //instance.getTicketByTicketLink(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketCategories', function() {
      it('should call getTicketCategories successfully', function(done) {
        //uncomment below and update the code to test getTicketCategories
        //instance.getTicketCategories(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketCategoryById', function() {
      it('should call getTicketCategoryById successfully', function(done) {
        //uncomment below and update the code to test getTicketCategoryById
        //instance.getTicketCategoryById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketCategoryCount', function() {
      it('should call getTicketCategoryCount successfully', function(done) {
        //uncomment below and update the code to test getTicketCategoryCount
        //instance.getTicketCategoryCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketCount', function() {
      it('should call getTicketCount successfully', function(done) {
        //uncomment below and update the code to test getTicketCount
        //instance.getTicketCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketCustomFieldById', function() {
      it('should call getTicketCustomFieldById successfully', function(done) {
        //uncomment below and update the code to test getTicketCustomFieldById
        //instance.getTicketCustomFieldById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketCustomFields', function() {
      it('should call getTicketCustomFields successfully', function(done) {
        //uncomment below and update the code to test getTicketCustomFields
        //instance.getTicketCustomFields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketLabelByLabelTicket', function() {
      it('should call getTicketLabelByLabelTicket successfully', function(done) {
        //uncomment below and update the code to test getTicketLabelByLabelTicket
        //instance.getTicketLabelByLabelTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketLayoutByContext', function() {
      it('should call getTicketLayoutByContext successfully', function(done) {
        //uncomment below and update the code to test getTicketLayoutByContext
        //instance.getTicketLayoutByContext(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketLayoutByContextByDepartment', function() {
      it('should call getTicketLayoutByContextByDepartment successfully', function(done) {
        //uncomment below and update the code to test getTicketLayoutByContextByDepartment
        //instance.getTicketLayoutByContextByDepartment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketLayoutByContextDepartmentJ', function() {
      it('should call getTicketLayoutByContextDepartmentJ successfully', function(done) {
        //uncomment below and update the code to test getTicketLayoutByContextDepartmentJ
        //instance.getTicketLayoutByContextDepartmentJ(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketLayoutContextJ', function() {
      it('should call getTicketLayoutContextJ successfully', function(done) {
        //uncomment below and update the code to test getTicketLayoutContextJ
        //instance.getTicketLayoutContextJ(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketMacroById', function() {
      it('should call getTicketMacroById successfully', function(done) {
        //uncomment below and update the code to test getTicketMacroById
        //instance.getTicketMacroById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketMacros', function() {
      it('should call getTicketMacros successfully', function(done) {
        //uncomment below and update the code to test getTicketMacros
        //instance.getTicketMacros(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketPriorities', function() {
      it('should call getTicketPriorities successfully', function(done) {
        //uncomment below and update the code to test getTicketPriorities
        //instance.getTicketPriorities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketPriorityById', function() {
      it('should call getTicketPriorityById successfully', function(done) {
        //uncomment below and update the code to test getTicketPriorityById
        //instance.getTicketPriorityById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketPriorityCount', function() {
      it('should call getTicketPriorityCount successfully', function(done) {
        //uncomment below and update the code to test getTicketPriorityCount
        //instance.getTicketPriorityCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketProblemById', function() {
      it('should call getTicketProblemById successfully', function(done) {
        //uncomment below and update the code to test getTicketProblemById
        //instance.getTicketProblemById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketProblemByIdTicket', function() {
      it('should call getTicketProblemByIdTicket successfully', function(done) {
        //uncomment below and update the code to test getTicketProblemByIdTicket
        //instance.getTicketProblemByIdTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketProblemCount', function() {
      it('should call getTicketProblemCount successfully', function(done) {
        //uncomment below and update the code to test getTicketProblemCount
        //instance.getTicketProblemCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketProblems', function() {
      it('should call getTicketProblems successfully', function(done) {
        //uncomment below and update the code to test getTicketProblems
        //instance.getTicketProblems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketProductById', function() {
      it('should call getTicketProductById successfully', function(done) {
        //uncomment below and update the code to test getTicketProductById
        //instance.getTicketProductById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketProductCount', function() {
      it('should call getTicketProductCount successfully', function(done) {
        //uncomment below and update the code to test getTicketProductCount
        //instance.getTicketProductCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketProducts', function() {
      it('should call getTicketProducts successfully', function(done) {
        //uncomment below and update the code to test getTicketProducts
        //instance.getTicketProducts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketStarByStarTicket', function() {
      it('should call getTicketStarByStarTicket successfully', function(done) {
        //uncomment below and update the code to test getTicketStarByStarTicket
        //instance.getTicketStarByStarTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketStarCount', function() {
      it('should call getTicketStarCount successfully', function(done) {
        //uncomment below and update the code to test getTicketStarCount
        //instance.getTicketStarCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketStars', function() {
      it('should call getTicketStars successfully', function(done) {
        //uncomment below and update the code to test getTicketStars
        //instance.getTicketStars(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketStatuseByStatuTicket', function() {
      it('should call getTicketStatuseByStatuTicket successfully', function(done) {
        //uncomment below and update the code to test getTicketStatuseByStatuTicket
        //instance.getTicketStatuseByStatuTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketStatuses', function() {
      it('should call getTicketStatuses successfully', function(done) {
        //uncomment below and update the code to test getTicketStatuses
        //instance.getTicketStatuses(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketWorkflowById', function() {
      it('should call getTicketWorkflowById successfully', function(done) {
        //uncomment below and update the code to test getTicketWorkflowById
        //instance.getTicketWorkflowById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketWorkflowCount', function() {
      it('should call getTicketWorkflowCount successfully', function(done) {
        //uncomment below and update the code to test getTicketWorkflowCount
        //instance.getTicketWorkflowCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTicketWorkflows', function() {
      it('should call getTicketWorkflows successfully', function(done) {
        //uncomment below and update the code to test getTicketWorkflows
        //instance.getTicketWorkflows(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTickets', function() {
      it('should call getTickets successfully', function(done) {
        //uncomment below and update the code to test getTickets
        //instance.getTickets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setTicketMacroByIdApplyByTicket', function() {
      it('should call setTicketMacroByIdApplyByTicket successfully', function(done) {
        //uncomment below and update the code to test setTicketMacroByIdApplyByTicket
        //instance.setTicketMacroByIdApplyByTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTicketByTicketActionLock', function() {
      it('should call updateTicketByTicketActionLock successfully', function(done) {
        //uncomment below and update the code to test updateTicketByTicketActionLock
        //instance.updateTicketByTicketActionLock(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTicketByTicketActionUnlock', function() {
      it('should call updateTicketByTicketActionUnlock successfully', function(done) {
        //uncomment below and update the code to test updateTicketByTicketActionUnlock
        //instance.updateTicketByTicketActionUnlock(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
